datetime <- strptime(paste(subsetData$Date, subsetData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
global_ActivePower <- as.numeric(subsetData$Global_active_power)
sub_Metering1 <- as.numeric(subsetData$Sub_metering_1)
sub_Metering2 <- as.numeric(subsetData$Sub_metering_2)
sub_Metering3 <- as.numeric(subsetData$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(datetime, sub_Metering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, sub_Metering2, type="l", col="red")
lines(datetime, sub_Metering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()